### ISSUE TITLE
Feature request: Tooltip on hover

### ISSUE THREAD

**Issue by daniel-sc** [SchweizerischeBundesbahnen/sbb-angular#110]
Currently the tooltip can only be triggered on click - we'd need the tooltip to trigger on hover of an arbitray elements. There should be configurable delays for show/hide.

**Additional context**
As an orientation one could check: https://ng-bootstrap.github.io/#/components/popover/examples

**Comment by timschoch** [comment]
To give you some context, this is one of our use cases: 
We have a data heavy table that our users need to skim fast and regularly need a subset of details to understand the context. Because this is a repetitive task, we need to prevent a back-and-forth between the master and detail views and we use progressive disclosure to do that:

![grafik](https://user-images.githubusercontent.com/10527318/61435934-f464fd80-a939-11e9-8d09-74cc57f2abf0.png)

The delay is necessary to allow the users to move their mouse cursor over the table, without annoying tooltips flipping up during the movement.

**Comment by kyubisation** [comment]
Opened feature request upstream: sbb-design-systems/sbb-design-system#6
