### ISSUE TITLE
AuthConfiguration in KeyCloak is required. 

### ISSUE THREAD

**Issue by mischahaenen** [SchweizerischeBundesbahnen/sbb-angular#185]
**Description**
I have testet the esta keycloak module and found, that we have to define in the AuthModule.forRoot Options an Auth-Configuration-Object. Also when it's just empty.

**To Reproduce**
1. Go to am-spp and create a new service & client with Grant Type: Authorization Code and Access Type Confidential.
2. Then install esta-keycloak module and import the AuthModule into your CoreModule without any Konfigurations
3. Let keycloak do his job...
4. See error: Client+is+not+allowed+to+initiate+browser+login+with+given+response_type.+Implicit+flow+is+disabled+for+the+client
5. When we define a empty object. {} it will work. 

**Expected behavior**
Either we define a empty Object and we mark the AuthConfig as required or we define a default value of the AuthConfig.

**Additional context**
Bitbucket Repo: https://code.sbb.ch/projects/KD_PW_CHECK/repos/pw-check-frontend/browse

**Comment by kyubisation** [comment]
Authorization Code with Access Code Confidential should require a client secret. In frontend code you should not use client secrets, since they can easily be extracted.
The reason why it works with {} is because then it uses the internal defaults. If you do not provide any options, our defaults will be used, which are { onLoad: 'check-sso', flow: 'implicit' }.

This is currently the intended behavior.

**Comment by mischahaenen** [comment]
Oh I see thank you for this information.
