### ISSUE TITLE
Datepicker parses input to early

### ISSUE THREAD

**Issue by daniel-sc** [SchweizerischeBundesbahnen/sbb-angular#30]
When entering `1.1.1` the date picker parses this input already to "1.1.2001", even though the user (probably) wanted to input `1.1.19` to get the date "1.1.2019" (depending on pivot).

Suggested solution: only parse input when there are two digits of the year present.

Version: 7.0.0

**Comment by kyubisation** [comment]
This behavior is intended.
This should be changeable via [FormControl.updateOn](https://angular.io/api/forms/AbstractControl#updateOn).
In regards to the slave datepicker triggering, this will be tracked in #36.

**Comment by daniel-sc** [comment]
@kyubisation I do not really agree here - to me `1.1.1` is not a meaningful date and should be treated similar to `1.1.` which is not parsed as well.

**Comment by kyubisation** [comment]
This is a complex issue, since 1.1.1 is a valid date and requiring two digits for years seems arbitrary, especially since you have no definitive way  of indicating this to users.
Is there a specific problem that you have with this behavior?

You could change this behavior by extending the [NativeDateAdapter](https://github.com/SchweizerischeBundesbahnen/sbb-angular/blob/master/projects/sbb-esta/angular-public/src/lib/datepicker/native-date-adapter.ts#L215) and registring it via `{ provide: DateAdapter, useClass: MyDateAdapter }`.

**Comment by daniel-sc** [comment]
To me it seems even more arbitrary to say `1.1.1` is a valid date but `1.1.` is not. I only suspect it will be rather confusing for users.. anyhow - well find workarounds..

**Comment by kyubisation** [comment]
1.1.1 => 1.1.2001
1.1. => 1.1.year?
The user is also not interrupted (anymore in master/slave with 8.0.0) when typing the year digits, so I'm not sure what is the exact problem. Please elaborate, if I'm missing the point here.

Something else I haven't mentioned previously. This behavior corresponds to sbb.ch, which is the de-facto requirement for this.
